-- ============================================================================
-- File             : lomonade_TD.sql
-- Author           : Franck BESSON
-- Date             : June 2017
-- Role             : Create tables dependencies
-- ============================================================================

--==== ITEM_POSSESSION dependencies ====

ALTER TABLE ITEM_POSSESSION
ADD CONSTRAINT FK_ITEM_POSSESSION_PLAYER_ID FOREIGN KEY (ITEM_POSSESSION_PLAYER_ID) REFERENCES PLAYER (PLAYER_ID);

ALTER TABLE ITEM_POSSESSION
ADD CONSTRAINT FK_ITEM_POSSESSION_ITEM_ID FOREIGN KEY (ITEM_POSSESSION_ITEM_ID) REFERENCES ITEM (ITEM_ID);

--==== COMPOSE dependencies ====

ALTER TABLE COMPOSE
ADD CONSTRAINT FK_COMPOSE_RECIPE_ID FOREIGN KEY (COMPOSE_RECIPE_ID) REFERENCES RECIPE (RECIPE_ID);

ALTER TABLE COMPOSE
ADD CONSTRAINT FK_COMPOSE_INGREDIENT_RECIPE_ID FOREIGN KEY (COMPOSE_INGREDIENT_RECIPE_ID) REFERENCES RECIPE (RECIPE_ID);

--==== SALE dependencies ====

ALTER TABLE SALE
ADD CONSTRAINT FK_SALE_DAY_NUMBER FOREIGN KEY (SALE_DAY_NUMBER) REFERENCES DAY (DAY_NUMBER);

ALTER TABLE SALE
ADD CONSTRAINT FK_SALE_RECIPE_ID FOREIGN KEY (SALE_RECIPE_ID) REFERENCES RECIPE (RECIPE_ID);

